version: '3.8'

services:
  app:
    build:
      context: .
      target: builder  # Use builder stage for faster rebuilds
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379
      - ENVIRONMENT=development
      - DEBUG=true
      - RELOAD=true
    volumes:
      - .:/app  # Live code reloading
      - /app/__pycache__  # Exclude cache
      - ./downloads:/app/downloads
      - ./logs:/app/logs
    depends_on:
      - redis
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data_dev:/data
    command: redis-server --appendonly yes

volumes:
  redis_data_dev: