services:
  - type: web
    name: vidnet-api
    env: python3
    plan: starter
    region: oregon
    branch: main
    healthCheckPath: /health
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python start.py
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: REDIS_URL
        fromService:
          type: redis
          name: vidnet-redis
          property: connectionString
    
  - type: redis
    name: vidnet-redis
    plan: starter
    region: oregon
    maxmemoryPolicy: allkeys-lru